name: lightman
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # ✅ Firebase packages
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.6.4

  # ✅ UI and utility packages
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  intl: ^0.17.0

  # ✅ Payment and WebView
  webview_flutter: ^4.4.2
  http: ^1.2.1
  url_launcher: ^6.2.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo.png
    - assets/images/small_logo.png
    - assets/images/woman.png
    - assets/images/onboarding.png
